name: libretro Core Info Package

on:
  # Trigger the workflow on push, but only for the master branch
  push:
    branches:
      - master
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  make_ppc_wiiu:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
  
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        chmod +x *.sh
        ./libretro-fetch.sh 
        ./libretro-build-wiiu.sh
    
    - name: Cache Source and all
      uses: actions/cache@v3
      with:
        path: |
            .
        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: source-wiiu
        path: build
        
  make_arm_3ds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
  
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        chmod +x *.sh
        ./libretro-fetch.sh
        ./libretro-build-ctr.sh
    
    - name: Cache Source and all
      uses: actions/cache@v3
      with:
        path: |
            .
      
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: source-3ds
        path: build
